name: 'CI setup'
description: 'Project basic setup'

runs:
  using: 'composite'

  steps:
    - name: setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install pnpm
      run: npm i pnpm@latest -g
      shell: bash

    - name: Setup npmrc
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      shell: bash

    - name: setup pnpm config
      run: pnpm config set store-dir .pnpm-store
      shell: bash

    - name: install dependencies
      run: pnpm install
      shell: bash
