name: Code Quality

on:
  push:
    branches-ignore:
      - 'main'

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-setup

      - name: Test
        run: pnpm run test:coverage

      - name: Eslint
        run: pnpm run lint:eslint

      - name: Prettier
        run: pnpm run lint:prettier
