name: Code Quality

on:
  push:
    branches-ignore:
      - 'main'

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/ci-setup
        name: 'Repo setup'

      - name: Test
        run: pnpm run test:coverage

      - name: Eslint
        run: pnpm run lint:eslint

      - name: Prettier
        run: pnpm run lint:prettier
